module.exports = {
  title: {
    text: 'My Portfolio',
    tagProps: {},
  },
  subtitle: {
    text: 'This is a collection of some posts i\'ve created for various companies',
    tagProps: {},
  },
  viewArchive: {
    text: '',
    tagProps: {},
  },
  dictionary: {
    post0: {
      image: 'Image 1.png',
      link: 'https://www.instagram.com/p/CTFXPeegTyN/?igshid=YmMyMTA2M2Y=',
      date: '',
      title: 'Grifols 0',
      company: '',
      tech: [],
      description: '',
    },
    post1: {
      image: 'Image 2.png',
      link: 'https://www.instagram.com/p/CSHdsc_rwuc/?igshid=YmMyMTA2M2Y%3D',
      date: '',
      title: 'Grifols 1',
      company: '',
      tech: [],
      description: '',
    },
    post2: {
      image: 'Image 3.png',
      link: 'https://www.instagram.com/p/CSZfCjErTx_/?igshid=YmMyMTA2M2Y%3D',
      date: '',
      title: 'Grifols 2',
      company: '',
      tech: [],
      description: '',
    },
    post3: {
      image: 'Image 4.png',
      link: 'https://www.instagram.com/p/CSrgxU-r-Oa/?igshid=YmMyMTA2M2Y%3D',
      date: '',
      title: 'Grifols 3',
      company: '',
      tech: [],
      description: '',
    },
    post4: {
      image: 'Image 5.png',
      link: 'https://www.instagram.com/p/CS9jmILrJjU/?igshid=YmMyMTA2M2Y%3D',
      date: '',
      title: 'Grifols 4',
      company: '',
      tech: [],
      description: '',
    },
    post5: {
      image: 'Image 6.png',
      link: 'https://www.instagram.com/p/CTPjdpKrRO7/?igshid=YmMyMTA2M2Y%3D',
      date: '',
      title: 'Grifols 5',
      company: '',
      tech: [],
      description: '',
    },
    post6: {
      image: 'Image 7.png',
      link: 'https://www.instagram.com/p/CT43GcvrNR7/?igshid=YmMyMTA2M2Y%3D',
      date: '',
      title: 'Grifols 6',
      company: '',
      tech: [],
      description: '',
    },
    post7: {
      image: 'Image 8.png',
      link: 'https://www.instagram.com/p/CUFoNT9gRWy/?igshid=ZWZhZTRhOWQ%3D',
      date: '',
      title: 'Grifols 7',
      company: '',
      tech: [],
      description: '',
    },
    post8: {
      image: 'Image 9.png',
      link: 'https://www.instagram.com/p/CUIT8JLLo1W/?igshid=ZWZhZTRhOWQ%3D',
      date: '',
      title: 'Grifols 8',
      company: '',
      tech: [],
      description: '',
    },
    post9: {
      image: 'Image 10.png',
      link: 'https://www.instagram.com/p/CUNdcilLFBA/?igshid=ZWZhZTRhOWQ%3D',
      date: '',
      title: 'Grifols 9',
      company: '',
      tech: [],
      description: '',
    },
    post10: {
      image: 'Image 11.png',
      link: 'https://www.instagram.com/p/CcA4ycqu_7R/?utm_source=ig_web_copy_link',
      date: '',
      title: 'Grifols 10',
      company: '',
      tech: [],
      description: '',
    },
    post11: {
      image: 'Image 12.png',
      link: 'https://www.instagram.com/p/Cc8KbhXuT-8/?igshid=ZWZhZTRhOWQ%3D',
      date: '',
      title: 'Grifols 11',
      company: '',
      tech: [],
      description: '',
    },
    post12: {
      image: 'Image 13.png',
      link: 'https://www.instagram.com/p/Cc8Dj_SsKtm/?igshid=ZWZhZTRhOWQ%3D',
      date: '',
      title: 'Grifols 12',
      company: '',
      tech: [],
      description: '',
    },
    post13: {
      image: 'Image 14.png',
      link: 'https://www.instagram.com/p/Cguy9nllrP4/?igshid=ZWZhZTRhOWQ%3D',
      date: '',
      title: 'Grifols 13',
      company: '',
      tech: [],
      description: '',
    },
    post14: {
      image: 'Image 15.png',
      link: 'https://www.instagram.com/p/CgzZvelsT_x/?igshid=ZWZhZTRhOWQ%3D',
      date: '',
      title: 'Grifols 14',
      company: '',
      tech: [],
      description: '',
    },
    post15: {
      image: 'Image 16.png',
      link: 'https://www.instagram.com/p/ChFOSRXg2_E/?utm_source=ig_web_copy_link',
      date: '',
      title: 'Grifols 15',
      company: '',
      tech: [],
      description: '',
    },
    post16: {
      image: 'Image 17.png',
      link: 'https://www.instagram.com/p/ChavEk5rl33/?utm_source=ig_web_copy_link',
      date: '',
      title: 'Grifols 16',
      company: '',
      tech: [],
      description: '',
    },
    post17: {
      image: 'Image 18.png',
      link: 'https://www.instagram.com/p/Chcm-eXOr3-/?utm_source=ig_web_copy_link',
      date: '',
      title: 'Grifols 17',
      company: '',
      tech: [],
      description: '',
    },
    post18: {
      image: 'Image 19.png',
      link: 'https://www.instagram.com/p/Ch2yZuWLhSY/?utm_source=ig_web_copy_link',
      date: '',
      title: 'Grifols 18',
      company: '',
      tech: [],
      description: '',
    },
    post19: {
      image: 'Image 20.png',
      link: 'https://www.facebook.com/grifolsplasma1940/photos/a.603993953051127/3749862078464283/',
      date: '',
      title: 'Grifols 19',
      company: '',
      tech: [],
      description: '',
    },
    post20: {
      image: 'Image 21.png',
      link:
        'https://www.facebook.com/grifolsplasma1940/posts/pfbid02dxb3xqpYKsAPyzw8uGRrMyD2QjanuWepS1XzPu1w9QvWxdz3CG2Sr1YomADAeVVZl',
      date: '',
      title: 'Grifols 20',
      company: '',
      tech: [],
      description: '',
    },
    post21: {
      image: 'Image 22.png',
      link:
        'https://m.facebook.com/story.php?story_fbid=pfbid024rM5YZxNe8RmAow9ubMTjC1Jnf89whvYqBuWyfdbZpWqTSoN7TdfLasURFeYKM2vl&id=603884296395426&mibextid=qC1gEa',
      date: '',
      title: 'Post 21',
      company: '',
      tech: [],
      description: '',
    },
    post22: {
      image: 'Image 23.png',
      link:
        'https://www.facebook.com/grifolsplasma1940/posts/pfbid02eVVdJCQm4AVREJWMoC35d1U3yNLH5gvtN8AAZLYMQum429asw49tytksn88qj8vPl',
      date: '',
      title: 'Post 22',
      company: '',
      tech: [],
      description: '',
    },
    post23: {
      image: 'Image 24.png',
      link:
        'https://www.facebook.com/grifolsplasma1940/posts/pfbid0cjGutxWyNb3qoCXRW7odKW4b4VRUdzgrdiDkFT6mi4wjMGC3cMJKB18foH94Btkvl',
      date: '',
      title: 'Post 23',
      company: '',
      tech: [],
      description: '',
    },
    post24: {
      image: 'Image 25.png',
      link:
        'https://www.facebook.com/grifolsplasma1940/posts/pfbid0LuFic6aMf4RHZ2TyfuSYiQBVDqn3DeEXqZYnFfQc2EdtcX8gKy5VZeRyiuz1DUuMl',
      date: '',
      title: 'Post 24',
      company: '',
      tech: [],
      description: '',
    },
    post25: {
      image: 'Image 26.png',
      link:
        'https://www.facebook.com/grifolsplasma1940/photos/a.603993953051127/5176032829180527/type=3&mibextid=qC1gEa&paipv=0&eav=AfbA0rB30g_k3RtWLLB27mh0W5ROzp8mGlC4BFT8lajXybpTa4KZaQ-vMT6LtzXtJt8&_rdr',
      date: '',
      title: 'Post 25',
      company: '',
      tech: [],
      description: '',
    },
    post26: {
      image: 'Image 27.png',
      link: 'https://www.facebook.com/grifolsplasma1940/photos/a.603993953051127/5185854148198395/',
      date: '',
      title: 'Post 26',
      company: '',
      tech: [],
      description: '',
    },
    post27: {
      image: 'Image 28.png',
      link: 'https://www.facebook.com/grifolsplasma1940/photos/a.603993953051127/5196186283831848/',
      date: '',
      title: 'Post 27',
      company: '',
      tech: [],
      description: '',
    },
    post28: {
      image: 'Image 29.png',
      link: 'https://www.facebook.com/grifolsplasma1940/photos/a.603993953051127/5228262243957585/',
      date: '',
      title: 'Post 28',
      company: '',
      tech: [],
      description: '',
    },
    post29: {
      image: 'Image 30.png',
      link: 'https://www.facebook.com/grifolsplasma1940/photos/a.603993953051127/4916620668455079/',
      date: '',
      title: 'Post 29',
      company: '',
      tech: [],
      description: '',
    },
    post30: {
      image: 'Image 31.png',
      link: 'https://www.facebook.com/grifolsplasma1940/photos/a.603993953051127/4956045204512625/',
      date: '',
      title: 'Post 30',
      company: '',
      tech: [],
      description: '',
    },
    post31: {
      image: 'Image 32.png',
      link:
        'https://www.facebook.com/grifolsplasma1940/photos/a.603993953051127/4956112611172551/?type=3&mibextid=qC1gEa&paipv=0&eav=AfaE78QSz9_BaDHe0RT_-K3tpCTDMN8hbaCRcrRqx86T2D_e68hSR3FwfKsoMrwXnNc&_rdr',
      date: '',
      title: 'Post 31',
      company: '',
      tech: [],
      description: '',
    },
    post32: {
      image: 'Image 33.png',
      link: 'https://www.facebook.com/grifolsplasma1940/photos/a.603993953051127/4956175164499629/',
      date: '',
      title: 'Post 32',
      company: '',
      tech: [],
      description: '',
    },
    tikTok1: {
      image: 'IMS Tiktok.png',
      link: '//www.tiktok.com/@imaninoirsocial_',
      date: '',
      title: 'tiktok 1',
      company: '',
      tech: [],
      description: '',
    },
    social1: {
      image: 'IMS IG.png',
      link: 'https://www.instagram.com/imaninoirsocial/',
      date: '',
      title: 'social 1',
      company: '',
      tech: [],
      description: '',
    },
    social2: {
      image: 'RateMY IG.png',
      link: 'https://www.instagram.com/ratemyyyplate/',
      date: '',
      title: 'social 2',
      company: '',
      tech: [],
      description: '',
    },
  },
};
